### ISSUE TITLE
make lib AOT compatible

### ISSUE THREAD

**Issue by systembugtj** [apoterenko/ngx-i18next#5]
ng build --prod show below errors. turn off aot with --aot=false, will remove the error.

Error message:
...$$_gendir/node_modules/angular2-i18next/TranslateI18NextModule.ngfactory.ts (21,154): Argument of type 'string' is not assignable to parameter of type 'OpaqueToken'.

OpaqueToken is deprecated. Use InjectableToken<string> instead?
https://angular.io/docs/ts/latest/api/core/index/OpaqueToken-class.html

**Comment by systembugtj** [comment]
Try make PR, but somehow local build isn't work. I think replace with InjectableToken<string> make fix the issue.

**Comment by leak** [comment]
Is there any progress in this area?

**Comment by Romanchuk** [comment]
@leak checkout alternative lib with AOT support https://www.npmjs.com/package/angular-i18next
